apiVersion: v1
kind: Pod
metadata:
  name: proxy-cyanite
spec:
  nodeSelector:
    role: loadbalancer
  containers:
  - name: cyanite-2003
    image: gcr.io/google_containers/proxy-to-service:v1
    args: [ "tcp", "2003", "cyanite.default" ]
    ports:
    - name: tcp
      protocol: TCP
      containerPort: 2003
      hostPort: 2003